@startuml
actor CSR as csr
control System as sys
actor DVLA as dvla
database Database as db
entity EmailHandler as email
actor Mechanic as mech

csr -> sys : Navigates to add new car screen
csr <-- sys : Request details about new car
csr -> sys : User inputs details

sys -> sys : Calculate rental price based on car details
sys -> dvla : Request car tax info
sys <-- dvla : Return information on cars tax

group #LightBlue Car is not taxed
  csr <-- sys : Request user to tax vehicle
  alt #LightCyan Request denied
    sys -> db : Mark car as unrentable
    sys -> email : Request reminder to be sent
    csr <-- email : Send user email reminder
  else #LightGreen Request accepted
    sys -> dvla : Direct user to DVLA
    csr -> dvla : Tax vehicle
  end
end

sys -> dvla : Request MOT information
sys <-- dvla : Return car MOT information
group #LightBlue Car is not MOT'd
  csr <-- sys : Request user to get car MOT'd
  csr -> mech : Send message to mechanic to MOT car
  sys -> db : Mark car as unrentable
end
sys -> db : Persist all details to storage
@enduml