@startuml
actor :Customer: as customer
(Rent car) as rentCar
(Extend rental) as rentExt
(Cancel rental) as rentCancel

customer --> (Register)
customer --> (Login)
customer --> (Browse available vehicles)
customer --> rentCar
customer --> rentExt
customer --> rentCancel
customer --> (Return a car)
customer --> (Pay for rental)
@enduml