@startuml
title Starting a new hire

start
  :Customer comes to the lot;
  :Check customers booking details;
  if (Valid booking) then (yes)
  else (no)
    :Offer customer choice of available vehicles;
    if (Customer wants a rental) then (yes)
      :Take payment;
      :Input rental details;
    else (no)
      #OrangeRed:Customer leaves with no rental;
      end
    endif
  endif

  :Mark car as rented;

  if (Customer purchases damage cover) then (yes)
    :Take cover payment;
    :Put details into database;
  else (no)
  endif

  #LightGreen:Hand over vehicle keys;
end
@enduml